'use client'

import { useState } from 'react'
import { ArrowLeft, Download, Eye, FileCheck2 } from 'lucide-react'
import { signupChallenge } from '@/data/challenges/signup'
import { Button } from '@/components/ui/button'
import CodeFlowApp from '@/components/codeflow-app'

export default function MentorPage() {
  const [value, setValue] = useState(JSON.stringify(signupChallenge, null, 2)); const [errors, setErrors] = useState<string[]>([]); const [preview, setPreview] = useState(false); const [customChallenge, setCustomChallenge] = useState(signupChallenge)
  const validate = () => { try { const parsed = JSON.parse(value); const required = ['id', 'title', 'fileName', 'scaffold', 'blocks', 'glossary', 'architecture']; const missing = required.filter((key) => !(key in parsed)); const nextErrors = missing.length ? missing.map((key) => `Missing required field: ${key}`) : !Array.isArray(parsed.blocks) ? ['blocks must be an array'] : parsed.blocks.length < 1 ? ['blocks must contain at least one block'] : []; setErrors(nextErrors); if (nextErrors.length === 0) setCustomChallenge(parsed) } catch (error) { setErrors([error instanceof Error ? error.message : 'Invalid JSON']) } }
  const download = () => { const blob = new Blob([JSON.stringify(signupChallenge, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'signup-challenge-template.json'; anchor.click(); URL.revokeObjectURL(url) }
  if (preview) return <div><div className="border-b border-[#292d35] bg-[#111318] px-5 py-3"><Button variant="ghost" onClick={() => setPreview(false)}><ArrowLeft data-icon="inline-start" />Back to editor</Button></div><CodeFlowApp challenge={customChallenge} sync={false} /></div>
  return <main className="min-h-screen bg-[#0d0f12] font-mono text-[#d4d4d4]"><header className="border-b border-[#292d35] bg-[#111318] px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="/" className="text-sm font-bold text-white">{'<>'} CodeFlow / Mentor mode</a><Button variant="outline" size="sm" onClick={download}><Download data-icon="inline-start" />Download template</Button></div></header><div className="mx-auto max-w-6xl p-6"><div className="max-w-2xl"><h1 className="text-2xl font-bold text-white">Create a challenge</h1><p className="mt-2 text-xs leading-6 text-[#858c98]">Paste a JSON definition matching the Challenge schema. Validate it, then preview the learning flow immediately.</p></div><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_320px]"><textarea value={value} onChange={(event) => setValue(event.target.value)} className="min-h-[620px] rounded-lg border border-[#343a46] bg-[#111318] p-4 font-mono text-xs leading-6 text-[#9cdcfe] outline-none focus:border-[#007acc]" spellCheck={false} /><aside className="rounded-lg border border-[#343a46] bg-[#15171d] p-4"><div className="flex items-center gap-2 text-sm font-bold text-white"><FileCheck2 className="size-4 text-[#4ec9b0]" /> Schema tools</div><Button className="mt-5 w-full" onClick={validate}>Validate</Button><Button variant="outline" className="mt-2 w-full" onClick={() => { validate(); setPreview(true) }}><Eye data-icon="inline-start" />Preview challenge</Button><div className="mt-5 text-xs">{errors.length === 0 ? <p className="text-[#4ec9b0]">No errors yet. Validate your definition to check it.</p> : <ul className="flex flex-col gap-2 text-[#f48771]">{errors.map((error) => <li key={error}>{error}</li>)}</ul>}</div></aside></div></div></main>
}
